<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="DFC"
           tests="3"
           failures="1"
           errors="0"
           skipped="0"
           time="20.890">
  <properties />
            <testcase name="logInToDFC" time="1.481" classname="com.hs18.Test.DFC.DfcLoginTest">
                <failure type="java.lang.AssertionError"
                  message="expected [Login not successful: invalid username or password!] but found [News Feed]"
              >
<![CDATA[java.lang.AssertionError: expected [Login not successful: invalid username or password!] but found [News Feed]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:496)
  org.testng.Assert.assertEquals(Assert.java:125)
  org.testng.Assert.assertEquals(Assert.java:178)
  org.testng.Assert.assertEquals(Assert.java:188)
  com.hs18.Test.DFC.DfcLoginTest.logInToDFC(DfcLoginTest.java:58)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  org.testng.TestRunner.privateRun(TestRunner.java:773)
  org.testng.TestRunner.run(TestRunner.java:623)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
  org.testng.SuiteRunner.run(SuiteRunner.java:259)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
  org.testng.TestNG.run(TestNG.java:1018)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="logInToDFC" time="2.635" classname="com.hs18.Test.DFC.DfcLoginTest" />
                <testcase name="changeStatus" time="16.774" classname="com.hs18.Test.DFC.DfcLoginTest" />
      
</testsuite>
